export const STROKE_COLOR = "#FFF";
export const FILL_COLOR_BODY = "#666";
export const FILL_COLOR_LEG = "#888";
export const STROKE_OPACITY = 0.65;
export const BODY_SIZE = 80;
export const LEG_WIDTH = 100;
export const LEG_HEIGHT = 40;
export const LEG_X = BODY_SIZE + LEG_WIDTH / 15;
export const BUTTON_WIDTH = LEG_WIDTH / 3;